packages:
  - "backend"
  - "web"
  - "mobile"
  - "extension"
  - "packages/*"

overrides:
  metro-cache: "0.80.12"
  "@types/react": "18.2.79"
allowBuilds:
  '@biomejs/biome': true
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  lefthook: true
  prisma: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@nestjs/core"
  - "@prisma/engines"
  - "bcrypt"
  - "esbuild"
  - "lefthook"
  - "prisma"

settings:
  confirmModulesPurge: false
